# Generated by Django 3.0 on 2020-11-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labwork6', '0002_auto_20201117_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='descriptionCourse',
            field=models.TextField(default=None, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='nameUnivercity',
            field=models.CharField(default=None, max_length=255, verbose_name='Название ВУЗа'),
        ),
    ]
