# Generated by Django 3.0 on 2020-11-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labwork6', '0003_auto_20201117_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='descriptionCourse',
            field=models.TextField(verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='nameUnivercity',
            field=models.CharField(max_length=255, verbose_name='Название ВУЗа'),
        ),
    ]
